using DotCarbon.Cli.Commands;
using Xunit;

namespace DotCarbon.Tests;

/// <summary>
/// Task 10.1: `carbon docs` generates an API reference by parsing plugin sources. The parser is pure,
/// so it is covered here against representative source; the end-to-end run over the real plugins and
/// the docs-site build are the integration check.
/// </summary>
public class DocsCommandTests
{
    private const string ClipboardSource = """
        using DotCarbon.Core.Bridge;
        using DotCarbon.Core.Plugins;

        namespace DotCarbon.Plugins.Clipboard;

        /// <summary>The system clipboard.</summary>
        [CarbonPlugin("Clipboard", description: "Read, write, and clear clipboard text.")]
        [CarbonPluginPlatform("desktop", "android", "ios")]
        [CarbonPermission("clipboard:default", "Allow all clipboard commands.", Commands = new[] { "clipboard:*" })]
        public partial class ClipboardPlugin : IPlugin
        {
            public string Namespace => "clipboard";

            /// <summary>Reads the current clipboard text.</summary>
            [CarbonCommand("read_text")]
            public Task<string> ReadText() => _provider.ReadText();

            [CarbonCommand("write_text")]
            public Task WriteText(WriteTextArgs args) => _provider.WriteText(args.Text);
        }
        """;

    [Fact]
    public void Parses_the_plugin_identity_and_platforms()
    {
        var plugin = Assert.Single(DocsCommand.Parse(ClipboardSource));

        Assert.Equal("clipboard", plugin.Namespace);
        Assert.Equal("Clipboard", plugin.Name);
        Assert.Equal("Read, write, and clear clipboard text.", plugin.Description);
        Assert.Equal(["desktop", "android", "ios"], plugin.Platforms);
    }

    [Fact]
    public void Parses_commands_with_argument_and_result_types()
    {
        var plugin = Assert.Single(DocsCommand.Parse(ClipboardSource));

        var read = plugin.Commands.Single(c => c.FullName == "clipboard:read_text");
        Assert.Null(read.Arguments);
        Assert.Equal("string", read.Result); // Task<string> is unwrapped.
        Assert.Equal("Reads the current clipboard text.", read.Summary);

        var write = plugin.Commands.Single(c => c.FullName == "clipboard:write_text");
        Assert.Equal("WriteTextArgs", write.Arguments);
        Assert.Equal("void", write.Result); // bare Task -> void.
    }

    [Fact]
    public void Parses_permissions_and_the_commands_they_grant()
    {
        var plugin = Assert.Single(DocsCommand.Parse(ClipboardSource));

        var permission = Assert.Single(plugin.Permissions);
        Assert.Equal("clipboard:default", permission.Identifier);
        Assert.Equal("Allow all clipboard commands.", permission.Description);
        Assert.Equal(["clipboard:*"], permission.Commands);
    }

    [Fact]
    public void A_class_without_the_plugin_attribute_is_ignored()
    {
        Assert.Empty(DocsCommand.Parse("public class NotAPlugin { public string Namespace => \"x\"; }"));
    }

    [Fact]
    public void Fully_qualified_attribute_names_are_recognized()
    {
        // Plugins sometimes write the attribute fully qualified; the parser must still see it.
        const string source = """
            namespace X;
            [global::DotCarbon.Core.Plugins.CarbonPlugin("Thing")]
            public partial class ThingPlugin
            {
                public string Namespace => "thing";
                [DotCarbon.Core.Bridge.CarbonCommand("go")]
                public void Go() { }
            }
            """;

        var plugin = Assert.Single(DocsCommand.Parse(source));
        Assert.Equal("thing", plugin.Namespace);
        Assert.Equal("thing:go", Assert.Single(plugin.Commands).FullName);
    }

    [Fact]
    public void Rendered_markdown_carries_frontmatter_a_generated_marker_and_a_command_row()
    {
        var markdown = DocsCommand.RenderMarkdown(DocsCommand.Parse(ClipboardSource), "Command reference");

        Assert.StartsWith("---", markdown);
        Assert.Contains("title: Command reference", markdown);
        // A "do not edit" marker so no one hand-edits generated output.
        Assert.Contains("Generated by `carbon docs`", markdown);
        Assert.Contains("| `clipboard:read_text` |", markdown);
        Assert.Contains("`clipboard:default`", markdown);
    }

    [Fact]
    public void A_pipe_in_a_summary_cannot_break_the_table()
    {
        const string source = """
            namespace X;
            [CarbonPlugin("Pipe")]
            public partial class PipePlugin
            {
                public string Namespace => "pipe";
                /// <summary>Takes a | b.</summary>
                [CarbonCommand("run")]
                public void Run() { }
            }
            """;

        var markdown = DocsCommand.RenderMarkdown(DocsCommand.Parse(source), "R");

        Assert.Contains(@"Takes a \| b.", markdown);
    }
}
