using System.CommandLine;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DotCarbon.Cli.Commands;

public static class TypesCommand
{
    public static Command Build()
    {
        var command = new Command("types", "Generate carbon.d.ts from your [CarbonCommand] methods");

        var projectOption = new Option<DirectoryInfo?>(
            "--project", "Path to the Carbon project (default: current directory)");
        var outOption = new Option<FileInfo?>(
            "--out", "Output path (default: ui/src/carbon.d.ts)");

        command.AddOption(projectOption);
        command.AddOption(outOption);
        command.SetHandler(Run, projectOption, outOption);
        return command;
    }

    private static void Run(DirectoryInfo? projectDir, FileInfo? outFile)
    {
        var root = projectDir?.FullName ?? Directory.GetCurrentDirectory();
        var carbonDir = Path.Combine(root, "src-carbon");
        var searchDir = Directory.Exists(carbonDir) ? carbonDir : root;

        var files = Directory.EnumerateFiles(searchDir, "*.cs", SearchOption.AllDirectories)
            .Where(p => !p.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}")
                     && !p.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}"))
            .ToList();

        var roots = files
            .Select(f => CSharpSyntaxTree.ParseText(File.ReadAllText(f)).GetCompilationUnitRoot())
            .ToList();

        var records = new Dictionary<string, List<(string Name, string Type)>>();
        foreach (var r in roots.SelectMany(r => r.DescendantNodes().OfType<RecordDeclarationSyntax>()))
        {
            var props = r.ParameterList?.Parameters
                .Select(p => (p.Identifier.Text, p.Type!.ToString()))
                .ToList() ?? new List<(string, string)>();
            records[r.Identifier.Text] = props;
        }

        var commands = new List<(string Name, string? ArgType, string ReturnType)>();

        foreach (var cls in roots.SelectMany(r => r.DescendantNodes().OfType<ClassDeclarationSyntax>()))
        {
            var implementsPlugin = cls.BaseList?.Types.Any(t => t.Type.ToString() == "IPlugin") ?? false;
            if (!implementsPlugin) continue;

            var ns = ExtractNamespace(cls);
            if (ns is null) continue;

            foreach (var method in cls.Members.OfType<MethodDeclarationSyntax>())
            {
                var attr = method.AttributeLists.SelectMany(a => a.Attributes)
                    .FirstOrDefault(a => a.Name.ToString() is "CarbonCommand" or "CarbonCommandAttribute");
                if (attr is null) continue;

                var nameArg = attr.ArgumentList?.Arguments.FirstOrDefault()?.Expression as LiteralExpressionSyntax;
                if (nameArg is null) continue;
                var cmd = $"{ns}:{nameArg.Token.ValueText}";

                var argType = method.ParameterList.Parameters.Count == 1
                    ? method.ParameterList.Parameters[0].Type!.ToString()
                    : null;

                commands.Add((cmd, argType, method.ReturnType.ToString()));
            }
        }

        var dts = Emit(commands.OrderBy(c => c.Name).ToList(), records);
        var target = outFile?.FullName ?? Path.Combine(root, "ui", "src", "carbon.d.ts");
        Directory.CreateDirectory(Path.GetDirectoryName(target)!);
        File.WriteAllText(target, dts);

        Console.ForegroundColor = ConsoleColor.Green;
        Console.WriteLine($"⚡ Generated {commands.Count} command type(s) → {target}");
        Console.ResetColor();
    }

    private static string? ExtractNamespace(ClassDeclarationSyntax cls)
    {
        var prop = cls.Members.OfType<PropertyDeclarationSyntax>()
            .FirstOrDefault(p => p.Identifier.Text == "Namespace");
        var literal = prop?.ExpressionBody?.Expression as LiteralExpressionSyntax
            ?? prop?.AccessorList?.Accessors
                .Select(a => a.ExpressionBody?.Expression as LiteralExpressionSyntax)
                .FirstOrDefault(e => e is not null);
        return literal?.Token.ValueText;
    }

    private static string Emit(
        List<(string Name, string? ArgType, string ReturnType)> commands,
        Dictionary<string, List<(string Name, string Type)>> records)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by `carbon types` — do not edit.");
        sb.AppendLine("import '@dotcarbon/api';");
        sb.AppendLine();
        sb.AppendLine("declare module '@dotcarbon/api' {");
        sb.AppendLine("    interface CarbonCommands {");
        foreach (var (name, argType, returnType) in commands)
        {
            var args = argType is null ? "void" : TsType(argType, records);
            var result = TsType(returnType, records);
            sb.AppendLine($"        '{name}': {{ args: {args}; result: {result} }};");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string TsType(string csType, Dictionary<string, List<(string Name, string Type)>> records)
    {
        csType = csType.Trim();

        if (csType == "Task" || csType == "void") return "void";
        if (csType.StartsWith("Task<") && csType.EndsWith(">"))
            return TsType(csType[5..^1], records);

        var nullable = csType.EndsWith("?");
        if (nullable) csType = csType[..^1].Trim();

        string ts;
        if (csType.EndsWith("[]"))
            ts = TsType(csType[..^2], records) + "[]";
        else
            ts = csType switch
            {
                "string" => "string",
                "bool" => "boolean",
                "int" or "long" or "short" or "byte" or "double" or "float" or "decimal" => "number",
                _ when records.TryGetValue(csType, out var props) =>
                    "{ " + string.Join("; ", props.Select(p => $"{Camel(p.Name)}: {TsType(p.Type, records)}")) + " }",
                _ => "unknown",
            };

        return nullable ? $"{ts} | null" : ts;
    }

    private static string Camel(string s) =>
        string.IsNullOrEmpty(s) ? s : char.ToLowerInvariant(s[0]) + s[1..];
}
