using DotCarbon.Core.Config;

namespace DotCarbon.Cli.Platforms;

/// <summary>Generates an Android (Gradle) shell. The .NET backend bridge lands in Phase 5.</summary>
internal sealed class AndroidPlatformGenerator : IPlatformGenerator
{
    public string Id => "android";
    public string DisplayName => "Android";

    public string ConfigSignature(CarbonConfig config)
    {
        var android = config.Bundle.Android;
        var package = Package(config);
        return $"{config.App.Name}|{package}|{config.App.Version}|{android.MinSdk}|{android.TargetSdk}|{android.CompileSdk}";
    }

    public IReadOnlyList<GeneratedFile> Generate(PlatformContext context)
    {
        var config = context.Config;
        var android = config.Bundle.Android;
        var name = config.App.Name;
        var package = Package(config);
        var packagePath = package.Replace('.', '/');
        var version = config.App.Version;
        var versionCode = VersionCode(version);

        const string header = "// Generated by Carbon — regenerated by `carbon platform sync android`.\n" +
                              "// Edit carbon.json (app.*, bundle.android) instead of this file.\n\n";

        return new List<GeneratedFile>
        {
            new("settings.gradle.kts", header +
                "pluginManagement {\n" +
                "    repositories { google(); mavenCentral(); gradlePluginPortal() }\n}\n" +
                "dependencyResolutionManagement {\n" +
                "    repositories { google(); mavenCentral() }\n}\n" +
                $"rootProject.name = \"{name}\"\n" +
                "include(\":app\")\n"),

            new("build.gradle.kts", header +
                "plugins {\n" +
                "    id(\"com.android.application\") version \"8.5.2\" apply false\n" +
                "    id(\"org.jetbrains.kotlin.android\") version \"2.0.20\" apply false\n}\n"),

            new("app/build.gradle.kts", header +
                "plugins {\n" +
                "    id(\"com.android.application\")\n" +
                "    id(\"org.jetbrains.kotlin.android\")\n}\n\n" +
                "android {\n" +
                $"    namespace = \"{package}\"\n" +
                $"    compileSdk = {android.CompileSdk}\n\n" +
                "    defaultConfig {\n" +
                $"        applicationId = \"{package}\"\n" +
                $"        minSdk = {android.MinSdk}\n" +
                $"        targetSdk = {android.TargetSdk}\n" +
                $"        versionCode = {versionCode}\n" +
                $"        versionName = \"{version}\"\n" +
                "    }\n\n" +
                "    buildTypes {\n        release {\n            isMinifyEnabled = false\n        }\n    }\n\n" +
                "    compileOptions {\n" +
                "        sourceCompatibility = JavaVersion.VERSION_17\n" +
                "        targetCompatibility = JavaVersion.VERSION_17\n    }\n" +
                "    kotlinOptions { jvmTarget = \"17\" }\n}\n\n" +
                "dependencies {\n" +
                "    implementation(\"androidx.appcompat:appcompat:1.7.0\")\n" +
                "    implementation(\"androidx.webkit:webkit:1.11.0\")\n" +
                "    // The Carbon <-> C# bridge is provided by DotCarbon.Host.Android (roadmap Phase 5).\n}\n"),

            new("app/src/main/AndroidManifest.xml",
                "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<!-- Generated by Carbon — regenerated by `carbon platform sync android`. -->\n" +
                "<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\">\n" +
                "    <uses-permission android:name=\"android.permission.INTERNET\" />\n\n" +
                "    <application\n" +
                $"        android:label=\"{name}\"\n" +
                "        android:allowBackup=\"true\"\n" +
                "        android:theme=\"@style/Theme.AppCompat.DayNight\">\n" +
                "        <activity\n" +
                "            android:name=\".MainActivity\"\n" +
                "            android:exported=\"true\">\n" +
                "            <intent-filter>\n" +
                "                <action android:name=\"android.intent.action.MAIN\" />\n" +
                "                <category android:name=\"android.intent.category.LAUNCHER\" />\n" +
                "            </intent-filter>\n" +
                "        </activity>\n" +
                "    </application>\n</manifest>\n"),

            new($"app/src/main/kotlin/{packagePath}/MainActivity.kt",
                $"package {package}\n\n" +
                "import android.os.Bundle\n" +
                "import android.webkit.WebView\n" +
                "import androidx.appcompat.app.AppCompatActivity\n\n" +
                "// Generated by Carbon — regenerated by `carbon platform sync android`.\n" +
                "// The Carbon <-> C# bridge is wired by DotCarbon.Host.Android (roadmap Phase 5).\n" +
                "class MainActivity : AppCompatActivity() {\n" +
                "    override fun onCreate(savedInstanceState: Bundle?) {\n" +
                "        super.onCreate(savedInstanceState)\n" +
                "        val webView = WebView(this)\n" +
                "        webView.settings.javaScriptEnabled = true\n" +
                "        setContentView(webView)\n" +
                "        // TODO(Phase 5): serve the embedded frontend and attach the Carbon bridge.\n" +
                "        webView.loadData(\n" +
                "            \"<h2>Carbon Android shell</h2><p>Backend host arrives in Phase 5.</p>\",\n" +
                "            \"text/html\", \"utf-8\")\n" +
                "    }\n}\n"),

            new("gradle.properties",
                "org.gradle.jvmargs=-Xmx2048m\n" +
                "android.useAndroidX=true\n" +
                "kotlin.code.style=official\n",
                Managed: false),

            new(".gitignore",
                ".gradle/\nbuild/\nlocal.properties\n*.apk\n*.aab\n",
                Managed: false),

            new("README.md",
                $"# {name} — Android shell\n\n" +
                "Generated by Carbon (`carbon platform add android`). Managed files are owned by\n" +
                "Carbon and regenerated by `carbon platform sync android` — change `carbon.json`\n" +
                "(`app.*`, `bundle.android`) rather than editing them. Files not tracked in\n" +
                "`.carbon-manifest.json` (e.g. `gradle.properties`, `.gitignore`) are yours.\n\n" +
                "The .NET backend bridge (Android WebView ↔ C#) is provided by\n" +
                "`DotCarbon.Host.Android` and lands in roadmap Phase 5; until then this is a native\n" +
                "shell placeholder.\n"),
        };
    }

    private static string Package(CarbonConfig config) =>
        string.IsNullOrWhiteSpace(config.Bundle.Android.Package)
            ? config.App.Identifier
            : config.Bundle.Android.Package!;

    private static long VersionCode(string version)
    {
        var parts = version.Split('.', '-')
            .Select(part => int.TryParse(part, out var value) ? value : 0)
            .ToArray();
        var major = parts.Length > 0 ? parts[0] : 0;
        var minor = parts.Length > 1 ? parts[1] : 0;
        var patch = parts.Length > 2 ? parts[2] : 0;
        return (major * 10000L) + (minor * 100L) + patch;
    }
}
