using DotCarbon.Core.Config;

namespace DotCarbon.Cli.Platforms;

/// <summary>
/// Generates a .NET Android (net10.0-android) app shell that references DotCarbon.Host.Android.
/// The backend commands run in-process via .NET Android; the WebView bridge is provided by the host.
/// </summary>
internal sealed class AndroidPlatformGenerator : IPlatformGenerator
{
    public string Id => "android";
    public string DisplayName => "Android";

    public string ConfigSignature(CarbonConfig config)
    {
        var android = config.Bundle.Android;
        return $"{config.App.Name}|{AppDisplayName(config)}|{Package(config)}|{config.App.Version}|{android.MinSdk}|{android.TargetSdk}|" +
               PermissionCatalog.Signature(config);
    }

    public IReadOnlyList<GeneratedFile> Generate(PlatformContext context)
    {
        var config = context.Config;
        var android = config.Bundle.Android;
        var name = config.App.Name;
        var displayName = AppDisplayName(config);
        var ns = Namespace(name);
        var package = Package(config);
        var version = config.App.Version;
        var versionCode = VersionCode(version);

        const string csHeader = "// Generated by Carbon — regenerated by `carbon platform sync android`.\n" +
                                "// Edit carbon.json (app.*, bundle.android) instead of this file.\n\n";

        var usesPermissions = string.Concat(
            new[] { "android.permission.INTERNET" }
                .Concat(PermissionCatalog.AndroidUsesPermissions(config))
                .Select(permission => $"    <uses-permission android:name=\"{permission}\" />\n"));

        return new List<GeneratedFile>
        {
            new($"{ns}.Android.csproj",
                "<!-- Generated by Carbon — regenerated by `carbon platform sync android`. -->\n" +
                "<Project Sdk=\"Microsoft.NET.Sdk\">\n\n" +
                "  <PropertyGroup>\n" +
                "    <TargetFramework>net10.0-android</TargetFramework>\n" +
                "    <OutputType>Exe</OutputType>\n" +
                "    <Nullable>enable</Nullable>\n" +
                "    <ImplicitUsings>enable</ImplicitUsings>\n" +
                $"    <ApplicationId>{package}</ApplicationId>\n" +
                $"    <ApplicationVersion>{versionCode}</ApplicationVersion>\n" +
                $"    <ApplicationDisplayVersion>{version}</ApplicationDisplayVersion>\n" +
                $"    <SupportedOSPlatformVersion>{android.MinSdk}</SupportedOSPlatformVersion>\n" +
                $"    <RootNamespace>{ns}</RootNamespace>\n" +
                "  </PropertyGroup>\n\n" +
                "  <ItemGroup>\n" +
                "    <PackageReference Include=\"DotCarbon.Host.Android\" Version=\"*\" />\n" +
                "    <!-- Reference a net-neutral class library holding your [CarbonCommand] classes\n" +
                "         so desktop and Android run the same backend, e.g.:\n" +
                "    <ProjectReference Include=\"..\\..\\..\\src-shared\\AppCommands.csproj\" /> -->\n" +
                "  </ItemGroup>\n\n" +
                "</Project>\n"),

            new("MainActivity.cs", csHeader +
                "using Android.App;\n" +
                "using Android.Content.PM;\n" +
                "using DotCarbon.Core.Runtime;\n" +
                "using DotCarbon.Host.Android;\n\n" +
                $"namespace {ns};\n\n" +
                "[Activity(\n" +
                $"    Label = \"{displayName}\",\n" +
                "    MainLauncher = true,\n" +
                "    ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.ScreenSize | ConfigChanges.UiMode)]\n" +
                "public class MainActivity : CarbonActivity\n" +
                "{\n" +
                "    protected override void ConfigureApp(CarbonApp app)\n" +
                "    {\n" +
                "        // Register your backend commands here, e.g. app.WithPlugin<AppCommands>();\n" +
                "        // Keep [CarbonCommand] classes in a shared class library referenced by both\n" +
                "        // this project and src-carbon so desktop and Android run the same backend.\n" +
                "    }\n" +
                "}\n"),

            new("AndroidManifest.xml",
                "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<!-- Generated by Carbon — regenerated by `carbon platform sync android`. -->\n" +
                "<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\">\n" +
                usesPermissions +
                $"    <application android:label=\"{displayName}\"\n" +
                "                 android:theme=\"@android:style/Theme.Material.Light.NoActionBar\" />\n" +
                "</manifest>\n"),

            new(".gitignore",
                "bin/\nobj/\n*.apk\n*.aab\n*.keystore\n",
                Managed: false),

            new("README.md",
                $"# {name} — Android (.NET Android)\n\n" +
                "Generated by Carbon (`carbon platform add android`). This is a `net10.0-android` app\n" +
                "that hosts your Carbon frontend in an Android WebView via `DotCarbon.Host.Android`.\n\n" +
                "Build it with `carbon bundle android` (needs the Android workload:\n" +
                "`dotnet workload install android`). Managed files regenerate on\n" +
                "`carbon platform sync android` — change `carbon.json` (`app.*`, `bundle.android`)\n" +
                "instead. `.gitignore` is yours.\n\n" +
                "To share your backend commands with desktop, put your `[CarbonCommand]` classes in a\n" +
                "platform-neutral class library and reference it from both this project and `src-carbon`,\n" +
                "then register them in `MainActivity.ConfigureApp`.\n"),
        };
    }

    private static string AppDisplayName(CarbonConfig config) =>
        string.IsNullOrWhiteSpace(config.App.DisplayName) ? config.App.Name : config.App.DisplayName!;

    private static string Package(CarbonConfig config) =>
        string.IsNullOrWhiteSpace(config.Bundle.Android.Package)
            ? config.App.Identifier
            : config.Bundle.Android.Package!;

    private static string Namespace(string name)
    {
        var slug = new string(name.Where(char.IsLetterOrDigit).ToArray());
        if (slug.Length == 0) slug = "CarbonApp";
        if (char.IsDigit(slug[0])) slug = "App" + slug;
        return slug;
    }

    private static long VersionCode(string version)
    {
        var parts = version.Split('.', '-')
            .Select(part => int.TryParse(part, out var value) ? value : 0)
            .ToArray();
        var major = parts.Length > 0 ? parts[0] : 0;
        var minor = parts.Length > 1 ? parts[1] : 0;
        var patch = parts.Length > 2 ? parts[2] : 0;
        return (major * 10000L) + (minor * 100L) + patch;
    }
}
