using DotCarbon.Core.Config;

namespace DotCarbon.Cli.Platforms;

/// <summary>
/// Generates a .NET Android (net10.0-android) app shell that references DotCarbon.Host.Android.
/// The backend commands run in-process via .NET Android; the WebView bridge is provided by the host.
/// </summary>
internal sealed class AndroidPlatformGenerator : IPlatformGenerator
{
    public string Id => "android";
    public string DisplayName => "Android";

    public string ConfigSignature(CarbonConfig config)
    {
        var android = config.Bundle.Android;
        return $"{config.App.Name}|{AppDisplayName(config)}|{Package(config)}|{config.App.Version}|{android.MinSdk}|{android.TargetSdk}|{config.Window.Orientation}|" +
               $"{string.Join(",", DeepLinkSchemes(config))}|" +
               PermissionCatalog.Signature(config);
    }

    /// <summary>Maps carbon.json's window.orientation onto the Activity's ScreenOrientation attribute.</summary>
    private static string ScreenOrientation(CarbonConfig config) => config.Window.Orientation?.Trim().ToLowerInvariant() switch
    {
        "portrait" => "    ScreenOrientation = ScreenOrientation.Portrait,\n",
        "landscape" => "    ScreenOrientation = ScreenOrientation.Landscape,\n",
        _ => string.Empty, // "any": leave it to the system
    };

    private static List<string> DeepLinkSchemes(CarbonConfig config) =>
        config.Bundle.Protocols
            .SelectMany(protocol => protocol.Schemes)
            .Select(scheme => scheme.Trim().TrimEnd(':'))
            .Where(scheme => scheme.Length > 0)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

    public IReadOnlyList<GeneratedFile> Generate(PlatformContext context)
    {
        var config = context.Config;
        var android = config.Bundle.Android;
        var name = config.App.Name;
        var displayName = AppDisplayName(config);
        var ns = Namespace(name);
        var package = Package(config);
        var version = config.App.Version;
        var versionCode = VersionCode(version);
        var hostReference = HostReference(context);

        // Deep-link schemes (bundle.protocols) become <intent-filter>s so the OS routes myscheme:// URLs
        // to the app; CarbonActivity delivers them to the DeepLink plugin.
        var orientation = ScreenOrientation(config);
        var schemes = DeepLinkSchemes(config);
        var deepLinkUsing = schemes.Count > 0 ? "using Android.Content;\n" : string.Empty;
        var intentFilters = string.Concat(schemes.Select(scheme =>
            "[IntentFilter(new[] { Intent.ActionView },\n" +
            "    Categories = new[] { Intent.CategoryDefault, Intent.CategoryBrowsable },\n" +
            $"    DataScheme = \"{scheme}\")]\n"));

        const string csHeader = "// Generated by Carbon — regenerated by `carbon platform sync android`.\n" +
                                "// Edit carbon.json (app.*, bundle.android) instead of this file.\n\n";

        var usesPermissions = string.Concat(
            new[] { "android.permission.INTERNET" }
                .Concat(PermissionCatalog.AndroidUsesPermissions(config))
                .Select(permission => $"    <uses-permission android:name=\"{permission}\" />\n"));

        return new List<GeneratedFile>
        {
            new($"{ns}.Android.csproj",
                "<!-- Generated by Carbon — regenerated by `carbon platform sync android`. -->\n" +
                "<Project Sdk=\"Microsoft.NET.Sdk\">\n\n" +
                "  <PropertyGroup>\n" +
                "    <TargetFramework>net10.0-android</TargetFramework>\n" +
                "    <OutputType>Exe</OutputType>\n" +
                "    <Nullable>enable</Nullable>\n" +
                "    <ImplicitUsings>enable</ImplicitUsings>\n" +
                $"    <ApplicationId>{package}</ApplicationId>\n" +
                $"    <ApplicationVersion>{versionCode}</ApplicationVersion>\n" +
                $"    <ApplicationDisplayVersion>{version}</ApplicationDisplayVersion>\n" +
                $"    <SupportedOSPlatformVersion>{android.MinSdk}</SupportedOSPlatformVersion>\n" +
                $"    <RootNamespace>{ns}</RootNamespace>\n" +
                "  </PropertyGroup>\n\n" +
                "  <ItemGroup>\n" +
                hostReference +
                "    <!-- The shared backend: the same [CarbonCommand] classes desktop runs. -->\n" +
                "    <ProjectReference Include=\"..\\..\\..\\src-shared\\AppLogic.csproj\" />\n" +
                "  </ItemGroup>\n\n" +
                "</Project>\n"),

            new("MainActivity.cs", csHeader +
                "using Android.App;\n" +
                "using Android.Content.PM;\n" +
                deepLinkUsing +
                "using DotCarbon.Core.Runtime;\n" +
                "using DotCarbon.Host.Android;\n\n" +
                $"namespace {ns};\n\n" +
                "[Activity(\n" +
                $"    Label = \"{displayName}\",\n" +
                "    MainLauncher = true,\n" +
                orientation +
                "    ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.ScreenSize | ConfigChanges.UiMode)]\n" +
                intentFilters +
                "public class MainActivity : CarbonActivity\n" +
                "{\n" +
                "    protected override void ConfigureApp(CarbonApp app)\n" +
                "    {\n" +
                "        // The same backend as desktop, from the shared library.\n" +
                "        app.Manage(new AppState());\n" +
                "        app.UsePlugin<AppCommands>();\n" +
                "    }\n" +
                "}\n"),

            new("AndroidManifest.xml",
                "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<!-- Generated by Carbon — regenerated by `carbon platform sync android`. -->\n" +
                "<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\">\n" +
                usesPermissions +
                $"    <application android:label=\"{displayName}\"\n" +
                "                 android:theme=\"@android:style/Theme.Material.Light.NoActionBar\" />\n" +
                "</manifest>\n"),

            new(".gitignore",
                "bin/\nobj/\n*.apk\n*.aab\n*.keystore\n",
                Managed: false),

            new("README.md",
                $"# {name} — Android (.NET Android)\n\n" +
                "Generated by Carbon (`carbon platform add android`). This is a `net10.0-android` app\n" +
                "that hosts your Carbon frontend in an Android WebView via `DotCarbon.Host.Android`.\n\n" +
                "Build it with `carbon bundle android` (needs the Android workload:\n" +
                "`dotnet workload install android`). Managed files regenerate on\n" +
                "`carbon platform sync android` — change `carbon.json` (`app.*`, `bundle.android`)\n" +
                "instead. `.gitignore` is yours.\n\n" +
                "To share your backend commands with desktop, put your `[CarbonCommand]` classes in a\n" +
                "platform-neutral class library and reference it from both this project and `src-carbon`,\n" +
                "then register them in `MainActivity.ConfigureApp`.\n"),
        };
    }

    private static string AppDisplayName(CarbonConfig config) =>
        string.IsNullOrWhiteSpace(config.App.DisplayName) ? config.App.Name : config.App.DisplayName!;

    private static string Package(CarbonConfig config) =>
        string.IsNullOrWhiteSpace(config.Bundle.Android.Package)
            ? config.App.Identifier
            : config.Bundle.Android.Package!;

    private static string HostReference(PlatformContext context)
    {
        if (Environment.GetEnvironmentVariable("CARBON_MOBILE_SMOKE_LOCAL_HOSTS") == "1" &&
            TryFindRepoHostProject(context.WorkingDir, "DotCarbon.Host.Android", out var hostProject))
        {
            var relative = Path.GetRelativePath(context.PlatformDir, hostProject)
                .Replace('/', '\\');
            return $"    <ProjectReference Include=\"{EscapeXml(relative)}\" />\n";
        }

        return "    <PackageReference Include=\"DotCarbon.Host.Android\" Version=\"*\" />\n";
    }

    private static bool TryFindRepoHostProject(string startDir, string projectName, out string hostProject)
    {
        var dir = new DirectoryInfo(Path.GetFullPath(startDir));
        while (dir is not null)
        {
            var candidate = Path.Combine(dir.FullName, "src", projectName, projectName + ".csproj");
            if (File.Exists(candidate))
            {
                hostProject = candidate;
                return true;
            }
            dir = dir.Parent;
        }

        hostProject = string.Empty;
        return false;
    }

    private static string EscapeXml(string value) =>
        value.Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("\"", "&quot;", StringComparison.Ordinal);

    private static string Namespace(string name)
    {
        var slug = new string(name.Where(char.IsLetterOrDigit).ToArray());
        if (slug.Length == 0) slug = "CarbonApp";
        if (char.IsDigit(slug[0])) slug = "App" + slug;
        return slug;
    }

    private static long VersionCode(string version)
    {
        var parts = version.Split('.', '-')
            .Select(part => int.TryParse(part, out var value) ? value : 0)
            .ToArray();
        var major = parts.Length > 0 ? parts[0] : 0;
        var minor = parts.Length > 1 ? parts[1] : 0;
        var patch = parts.Length > 2 ? parts[2] : 0;
        return (major * 10000L) + (minor * 100L) + patch;
    }
}
