using DotCarbon.Core.Config;

namespace DotCarbon.Cli.Platforms;

/// <summary>
/// Generates a .NET iOS (net10.0-ios) app shell that references DotCarbon.Host.iOS. The backend
/// commands run in-process via .NET iOS; the WKWebView bridge is provided by the host.
/// </summary>
internal sealed class IosPlatformGenerator : IPlatformGenerator
{
    public string Id => "ios";
    public string DisplayName => "iOS";

    public string ConfigSignature(CarbonConfig config)
    {
        var ios = config.Bundle.Ios;
        return $"{config.App.Name}|{BundleId(config)}|{config.App.Version}|{ios.MinimumOSVersion}|{ios.DevelopmentTeam}";
    }

    public IReadOnlyList<GeneratedFile> Generate(PlatformContext context)
    {
        var config = context.Config;
        var ios = config.Bundle.Ios;
        var name = config.App.Name;
        var ns = Namespace(name);
        var bundleId = BundleId(config);
        var version = config.App.Version;
        var buildNumber = BuildNumber(version);

        const string csHeader = "// Generated by Carbon — regenerated by `carbon platform sync ios`.\n" +
                                "// Edit carbon.json (app.*, bundle.ios) instead of this file.\n\n";

        var teamProp = string.IsNullOrWhiteSpace(ios.DevelopmentTeam)
            ? string.Empty
            : $"    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>\n";

        return new List<GeneratedFile>
        {
            new($"{ns}.iOS.csproj",
                "<!-- Generated by Carbon — regenerated by `carbon platform sync ios`. -->\n" +
                "<Project Sdk=\"Microsoft.NET.Sdk\">\n\n" +
                "  <PropertyGroup>\n" +
                "    <TargetFramework>net10.0-ios</TargetFramework>\n" +
                "    <OutputType>Exe</OutputType>\n" +
                "    <Nullable>enable</Nullable>\n" +
                "    <ImplicitUsings>enable</ImplicitUsings>\n" +
                $"    <ApplicationId>{bundleId}</ApplicationId>\n" +
                $"    <ApplicationVersion>{buildNumber}</ApplicationVersion>\n" +
                $"    <ApplicationDisplayVersion>{version}</ApplicationDisplayVersion>\n" +
                $"    <SupportedOSPlatformVersion>{ios.MinimumOSVersion}</SupportedOSPlatformVersion>\n" +
                $"    <RootNamespace>{ns}</RootNamespace>\n" +
                teamProp +
                "  </PropertyGroup>\n\n" +
                "  <ItemGroup>\n" +
                "    <PackageReference Include=\"DotCarbon.Host.iOS\" Version=\"*\" />\n" +
                "    <!-- Reference a net-neutral class library holding your [CarbonCommand] classes\n" +
                "         so desktop and iOS run the same backend, e.g.:\n" +
                "    <ProjectReference Include=\"..\\..\\..\\src-shared\\AppCommands.csproj\" /> -->\n" +
                "  </ItemGroup>\n\n" +
                "</Project>\n"),

            new("Main.cs", csHeader +
                "using UIKit;\n\n" +
                $"namespace {ns};\n\n" +
                "public static class Program\n" +
                "{\n" +
                "    static void Main(string[] args)\n" +
                "    {\n" +
                "        UIApplication.Main(args, null, typeof(AppDelegate));\n" +
                "    }\n" +
                "}\n"),

            new("AppDelegate.cs", csHeader +
                "using DotCarbon.Core.Runtime;\n" +
                "using DotCarbon.Host.iOS;\n" +
                "using Foundation;\n\n" +
                $"namespace {ns};\n\n" +
                "[Register(\"AppDelegate\")]\n" +
                "public class AppDelegate : CarbonAppDelegate\n" +
                "{\n" +
                "    protected override void ConfigureApp(CarbonApp app)\n" +
                "    {\n" +
                "        // Register your backend commands here, e.g. app.WithPlugin<AppCommands>();\n" +
                "        // Keep [CarbonCommand] classes in a shared class library referenced by both\n" +
                "        // this project and src-carbon so desktop and iOS run the same backend.\n" +
                "    }\n" +
                "}\n"),

            new("Info.plist",
                "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n" +
                "<plist version=\"1.0\">\n<dict>\n" +
                $"    <key>CFBundleDisplayName</key><string>{name}</string>\n" +
                $"    <key>CFBundleIdentifier</key><string>{bundleId}</string>\n" +
                $"    <key>CFBundleShortVersionString</key><string>{version}</string>\n" +
                $"    <key>CFBundleVersion</key><string>{buildNumber}</string>\n" +
                "    <key>LSRequiresIPhoneOS</key><true/>\n" +
                "    <key>UILaunchScreen</key><dict/>\n" +
                "    <key>UIDeviceFamily</key><array><integer>1</integer><integer>2</integer></array>\n" +
                "    <key>UISupportedInterfaceOrientations</key>\n" +
                "    <array>\n" +
                "        <string>UIInterfaceOrientationPortrait</string>\n" +
                "        <string>UIInterfaceOrientationLandscapeLeft</string>\n" +
                "        <string>UIInterfaceOrientationLandscapeRight</string>\n" +
                "    </array>\n" +
                "</dict>\n</plist>\n"),

            new("Entitlements.plist",
                "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n" +
                "<plist version=\"1.0\">\n<dict>\n</dict>\n</plist>\n"),

            new(".gitignore",
                "bin/\nobj/\n*.ipa\n*.app/\n",
                Managed: false),

            new("README.md",
                $"# {name} — iOS (.NET iOS)\n\n" +
                "Generated by Carbon (`carbon platform add ios`). This is a `net10.0-ios` app that\n" +
                "hosts your Carbon frontend in a WKWebView via `DotCarbon.Host.iOS`.\n\n" +
                "Build it on a Mac with Xcode + the iOS workload (`dotnet workload install ios`):\n\n" +
                "```bash\n" +
                "carbon bundle ios --simulator   # or --device / --archive\n" +
                "carbon dev ios                  # build + run on a booted simulator\n" +
                "```\n\n" +
                "Managed files regenerate on `carbon platform sync ios` — change `carbon.json`\n" +
                "(`app.*`, `bundle.ios`) instead. `.gitignore` is yours. Device/archive builds need a\n" +
                "signing identity and provisioning profile (`bundle.ios.developmentTeam`).\n\n" +
                "To share your backend commands with desktop, put your `[CarbonCommand]` classes in a\n" +
                "platform-neutral class library and reference it from both this project and `src-carbon`.\n"),
        };
    }

    private static string BundleId(CarbonConfig config) =>
        string.IsNullOrWhiteSpace(config.Bundle.Ios.BundleIdentifier)
            ? config.App.Identifier
            : config.Bundle.Ios.BundleIdentifier!;

    private static string Namespace(string name)
    {
        var slug = new string(name.Where(char.IsLetterOrDigit).ToArray());
        if (slug.Length == 0) slug = "CarbonApp";
        if (char.IsDigit(slug[0])) slug = "App" + slug;
        return slug;
    }

    private static long BuildNumber(string version)
    {
        var parts = version.Split('.', '-')
            .Select(part => int.TryParse(part, out var value) ? value : 0)
            .ToArray();
        var major = parts.Length > 0 ? parts[0] : 0;
        var minor = parts.Length > 1 ? parts[1] : 0;
        var patch = parts.Length > 2 ? parts[2] : 0;
        return (major * 10000L) + (minor * 100L) + patch;
    }
}
