using DotCarbon.Core.Config;

namespace DotCarbon.Cli.Platforms;

/// <summary>Generates an iOS shell as a reproducible XcodeGen project. WKWebView host lands in Phase 6.</summary>
internal sealed class IosPlatformGenerator : IPlatformGenerator
{
    public string Id => "ios";
    public string DisplayName => "iOS";

    public string ConfigSignature(CarbonConfig config)
    {
        var ios = config.Bundle.Ios;
        return $"{config.App.Name}|{BundleId(config)}|{config.App.Version}|{ios.MinimumOSVersion}|{ios.DevelopmentTeam}";
    }

    public IReadOnlyList<GeneratedFile> Generate(PlatformContext context)
    {
        var config = context.Config;
        var ios = config.Bundle.Ios;
        var name = config.App.Name;
        var product = Sanitize(name);
        var bundleId = BundleId(config);
        var version = config.App.Version;
        var buildNumber = BuildNumber(version);

        var teamSetting = string.IsNullOrWhiteSpace(ios.DevelopmentTeam)
            ? string.Empty
            : $"        DEVELOPMENT_TEAM: {ios.DevelopmentTeam}\n";

        return new List<GeneratedFile>
        {
            new("project.yml",
                "# Generated by Carbon — regenerated by `carbon platform sync ios`.\n" +
                "# Edit carbon.json (app.*, bundle.ios) instead. Run `xcodegen generate` to build the .xcodeproj.\n" +
                $"name: {product}\n" +
                "options:\n" +
                "  deploymentTarget:\n" +
                $"    iOS: \"{ios.MinimumOSVersion}\"\n" +
                "targets:\n" +
                "  App:\n" +
                "    type: application\n" +
                "    platform: iOS\n" +
                "    sources:\n" +
                "      - path: Sources\n" +
                "    info:\n" +
                "      path: Sources/App/Info.plist\n" +
                "    settings:\n" +
                "      base:\n" +
                $"        PRODUCT_BUNDLE_IDENTIFIER: {bundleId}\n" +
                $"        PRODUCT_NAME: {product}\n" +
                $"        MARKETING_VERSION: {version}\n" +
                $"        CURRENT_PROJECT_VERSION: {buildNumber}\n" +
                $"        INFOPLIST_KEY_CFBundleDisplayName: {name}\n" +
                teamSetting),

            new("Sources/App/CarbonApp.swift",
                "import UIKit\n" +
                "import WebKit\n\n" +
                "// Generated by Carbon — regenerated by `carbon platform sync ios`.\n" +
                "// The Carbon <-> C# bridge is provided by DotCarbon.Host.iOS (roadmap Phase 6).\n" +
                "@main\n" +
                "class AppDelegate: UIResponder, UIApplicationDelegate {\n" +
                "    var window: UIWindow?\n\n" +
                "    func application(_ application: UIApplication,\n" +
                "                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {\n" +
                "        let window = UIWindow(frame: UIScreen.main.bounds)\n" +
                "        let controller = UIViewController()\n" +
                "        let webView = WKWebView(frame: .zero)\n" +
                "        controller.view = webView\n" +
                "        // TODO(Phase 6): serve the embedded frontend and attach the Carbon bridge.\n" +
                "        webView.loadHTMLString(\"<h2>Carbon iOS shell</h2><p>Backend host arrives in Phase 6.</p>\", baseURL: nil)\n" +
                "        window.rootViewController = controller\n" +
                "        window.makeKeyAndVisible()\n" +
                "        self.window = window\n" +
                "        return true\n" +
                "    }\n}\n"),

            new("Sources/App/Info.plist",
                "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n" +
                "<plist version=\"1.0\">\n<dict>\n" +
                "    <key>CFBundleIdentifier</key><string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>\n" +
                "    <key>CFBundleName</key><string>$(PRODUCT_NAME)</string>\n" +
                $"    <key>CFBundleDisplayName</key><string>{name}</string>\n" +
                $"    <key>CFBundleShortVersionString</key><string>{version}</string>\n" +
                $"    <key>CFBundleVersion</key><string>{buildNumber}</string>\n" +
                "    <key>UILaunchScreen</key><dict/>\n" +
                "    <key>UIApplicationSupportsIndirectInputEvents</key><true/>\n" +
                "</dict>\n</plist>\n"),

            new(".gitignore",
                "*.xcodeproj/\nDerivedData/\nbuild/\n.build/\n",
                Managed: false),

            new("README.md",
                $"# {name} — iOS shell\n\n" +
                "Generated by Carbon (`carbon platform add ios`). Managed files are owned by Carbon\n" +
                "and regenerated by `carbon platform sync ios` — change `carbon.json` (`app.*`,\n" +
                "`bundle.ios`) rather than editing them. Files not tracked in `.carbon-manifest.json`\n" +
                "(e.g. `.gitignore`) are yours.\n\n" +
                "The project is defined with [XcodeGen](https://github.com/yonaskolb/XcodeGen); run\n" +
                "`xcodegen generate` to produce the `.xcodeproj`. The .NET backend bridge\n" +
                "(WKWebView ↔ C#) is provided by `DotCarbon.Host.iOS` and lands in roadmap Phase 6.\n"),
        };
    }

    private static string BundleId(CarbonConfig config) =>
        string.IsNullOrWhiteSpace(config.Bundle.Ios.BundleIdentifier)
            ? config.App.Identifier
            : config.Bundle.Ios.BundleIdentifier!;

    private static string Sanitize(string name)
    {
        var slug = new string(name.Where(ch => char.IsLetterOrDigit(ch)).ToArray());
        return string.IsNullOrEmpty(slug) ? "CarbonApp" : slug;
    }

    private static long BuildNumber(string version)
    {
        var parts = version.Split('.', '-')
            .Select(part => int.TryParse(part, out var value) ? value : 0)
            .ToArray();
        var major = parts.Length > 0 ? parts[0] : 0;
        var minor = parts.Length > 1 ? parts[1] : 0;
        var patch = parts.Length > 2 ? parts[2] : 0;
        return (major * 10000L) + (minor * 100L) + patch;
    }
}
