// AUTO-GENERATED by `carbon types` — do not edit.
/// <reference path="./carbon.d.ts" />
import { invoke } from '@dotcarbon/api';
import type { CarbonCommands } from '@dotcarbon/api';

export const app = {
    /** app:greet */
    greet: (args: CarbonCommands['app:greet']['args']): Promise<CarbonCommands['app:greet']['result']> => invoke('app:greet', args),
};
