using System.Text;
using DotCarbon.Core.Config;

namespace DotCarbon.Cli.Bundling;

/// <summary>
/// Generates the NSIS script for a Windows <c>.exe</c> setup — the second Windows target alongside the
/// WiX MSI. MSI suits managed/enterprise deployment; NSIS produces a smaller, self-contained installer
/// that can install per-user with no elevation prompt, which is what most desktop apps want.
/// </summary>
internal static class NsisInstaller
{
    /// <summary>
    /// Builds the <c>.nsi</c> script. <paramref name="outDir"/> is the published app directory whose
    /// entire contents get installed; <paramref name="exeName"/> is the launcher inside it.
    /// </summary>
    public static string Script(
        CarbonConfig config,
        string outDir,
        string exeName,
        string? webView2Installer,
        string? iconIco,
        string outputExe)
    {
        var nsis = config.Bundle.Windows.Nsis;
        var perMachine = nsis.InstallMode.Equals("perMachine", StringComparison.OrdinalIgnoreCase);
        var name = string.IsNullOrWhiteSpace(config.App.Name)
            ? Path.GetFileNameWithoutExtension(exeName)
            : config.App.Name;
        var publisher = config.Bundle.Publisher ?? name;
        // The uninstall registry key must be stable across versions or upgrades orphan the old entry.
        var uninstallKey = $@"Software\Microsoft\Windows\CurrentVersion\Uninstall\{config.App.Identifier}";
        var script = new StringBuilder();

        script.AppendLine("; Generated by Carbon — regenerated on every `carbon bundle desktop`.");
        script.AppendLine("Unicode true");
        script.AppendLine("!include \"MUI2.nsh\"");
        script.AppendLine("!include \"FileFunc.nsh\"");
        script.AppendLine("!include \"LogicLib.nsh\"");
        script.AppendLine();
        script.AppendLine($"Name \"{Escape(name)}\"");
        script.AppendLine($"OutFile \"{Escape(outputExe)}\"");
        script.AppendLine($"VIProductVersion \"{FileVersion(config.App.Version)}\"");
        script.AppendLine($"VIAddVersionKey \"ProductName\" \"{Escape(name)}\"");
        script.AppendLine($"VIAddVersionKey \"CompanyName\" \"{Escape(publisher)}\"");
        script.AppendLine($"VIAddVersionKey \"FileVersion\" \"{FileVersion(config.App.Version)}\"");
        script.AppendLine($"VIAddVersionKey \"ProductVersion\" \"{Escape(config.App.Version)}\"");
        script.AppendLine($"VIAddVersionKey \"LegalCopyright\" \"{Escape(publisher)}\"");
        script.AppendLine($"VIAddVersionKey \"FileDescription\" \"{Escape(name)} installer\"");
        script.AppendLine();

        if (perMachine)
        {
            script.AppendLine($"InstallDir \"$PROGRAMFILES64\\{Escape(name)}\"");
            script.AppendLine("RequestExecutionLevel admin");
        }
        else
        {
            // Per-user: no UAC prompt, and the app lands somewhere the user can always write.
            script.AppendLine($"InstallDir \"$LOCALAPPDATA\\Programs\\{Escape(name)}\"");
            script.AppendLine("RequestExecutionLevel user");
        }

        script.AppendLine($"InstallDirRegKey HKCU \"{uninstallKey}\" \"InstallLocation\"");
        script.AppendLine("ShowInstDetails show");
        script.AppendLine("ShowUnInstDetails show");
        script.AppendLine();

        if (iconIco is not null)
        {
            script.AppendLine($"!define MUI_ICON \"{Escape(iconIco)}\"");
            script.AppendLine($"!define MUI_UNICON \"{Escape(iconIco)}\"");
        }

        script.AppendLine("!define MUI_ABORTWARNING");
        script.AppendLine("!insertmacro MUI_PAGE_WELCOME");
        if (!string.IsNullOrWhiteSpace(nsis.License))
            script.AppendLine($"!insertmacro MUI_PAGE_LICENSE \"{Escape(nsis.License)}\"");
        script.AppendLine("!insertmacro MUI_PAGE_DIRECTORY");
        script.AppendLine("!insertmacro MUI_PAGE_INSTFILES");
        // Offer to launch on finish, but not during a silent install.
        script.AppendLine($"!define MUI_FINISHPAGE_RUN \"$INSTDIR\\{Escape(exeName)}\"");
        script.AppendLine("!insertmacro MUI_PAGE_FINISH");
        script.AppendLine("!insertmacro MUI_UNPAGE_CONFIRM");
        script.AppendLine("!insertmacro MUI_UNPAGE_INSTFILES");
        script.AppendLine($"!insertmacro MUI_LANGUAGE \"{Escape(nsis.Language)}\"");
        script.AppendLine();

        script.AppendLine("Section \"Install\"");
        script.AppendLine("  SetOutPath \"$INSTDIR\"");
        // Recursively install everything the publish produced, preserving the directory layout.
        // Paths are joined with an explicit backslash rather than Path.Combine: these are Windows
        // paths regardless of the host generating the script.
        script.AppendLine($"  File /r \"{Escape(outDir.TrimEnd('\\', '/'))}\\*.*\"");
        script.AppendLine();

        if (webView2Installer is not null)
        {
            // WebView2 is a hard runtime dependency; the bootstrapper no-ops when it is already present.
            var bootstrapper = Escape(WindowsFileName(webView2Installer));
            script.AppendLine("  ; WebView2 runtime — the bootstrapper exits immediately if it is installed.");
            script.AppendLine($"  File \"{Escape(webView2Installer)}\"");
            script.AppendLine($"  ExecWait '\"$INSTDIR\\{bootstrapper}\" /silent /install'");
            script.AppendLine($"  Delete \"$INSTDIR\\{bootstrapper}\"");
            script.AppendLine();
        }

        script.AppendLine("  CreateShortcut \"$SMPROGRAMS\\" + Escape(name) + ".lnk\" \"$INSTDIR\\" + Escape(exeName) + "\"");
        script.AppendLine("  WriteUninstaller \"$INSTDIR\\uninstall.exe\"");
        script.AppendLine();

        // Add/Remove Programs metadata, so the app is uninstallable the way users expect.
        // Values are pre-composed: user-supplied text goes through Escape, NSIS variables ($INSTDIR)
        // must NOT — Escape doubles '$', which would turn them into literals.
        script.AppendLine("  ; Add/Remove Programs entry.");
        foreach (var (key, value) in new[]
        {
            ("DisplayName", Escape(name)),
            ("DisplayVersion", Escape(config.App.Version)),
            ("Publisher", Escape(publisher)),
            ("InstallLocation", "$INSTDIR"),
            ("UninstallString", "$\\\"$INSTDIR\\uninstall.exe$\\\""),
            ("QuietUninstallString", "$\\\"$INSTDIR\\uninstall.exe$\\\" /S"),
            ("DisplayIcon", $"$INSTDIR\\{Escape(exeName)}"),
        })
        {
            script.AppendLine($"  WriteRegStr HKCU \"{uninstallKey}\" \"{key}\" \"{value}\"");
        }

        script.AppendLine("  WriteRegDWORD HKCU \"" + uninstallKey + "\" \"NoModify\" 1");
        script.AppendLine("  WriteRegDWORD HKCU \"" + uninstallKey + "\" \"NoRepair\" 1");
        script.AppendLine("  ${GetSize} \"$INSTDIR\" \"/S=0K\" $0 $1 $2");
        script.AppendLine($"  IntFmt $0 \"0x%08X\" $0");
        script.AppendLine($"  WriteRegDWORD HKCU \"{uninstallKey}\" \"EstimatedSize\" \"$0\"");

        AppendFileAssociations(script, config, exeName);
        AppendProtocols(script, config, exeName);

        script.AppendLine("SectionEnd");
        script.AppendLine();

        script.AppendLine("Section \"Uninstall\"");
        script.AppendLine($"  Delete \"$SMPROGRAMS\\{Escape(name)}.lnk\"");
        script.AppendLine("  RMDir /r \"$INSTDIR\"");
        script.AppendLine($"  DeleteRegKey HKCU \"{uninstallKey}\"");

        foreach (var association in config.Bundle.FileAssociations.Where(item => item.Extensions.Count > 0))
        {
            var progId = config.App.Identifier + "." + association.Extensions[0].TrimStart('.');
            foreach (var extension in association.Extensions)
                script.AppendLine($"  DeleteRegKey HKCU \"Software\\Classes\\.{Escape(extension.TrimStart('.'))}\"");
            script.AppendLine($"  DeleteRegKey HKCU \"Software\\Classes\\{Escape(progId)}\"");
        }

        foreach (var protocol in config.Bundle.Protocols.SelectMany(item => item.Schemes).Distinct())
            script.AppendLine($"  DeleteRegKey HKCU \"Software\\Classes\\{Escape(protocol)}\"");

        script.AppendLine("SectionEnd");
        return script.ToString();
    }

    private static void AppendFileAssociations(StringBuilder script, CarbonConfig config, string exeName)
    {
        var associations = config.Bundle.FileAssociations.Where(item => item.Extensions.Count > 0).ToList();
        if (associations.Count == 0) return;

        script.AppendLine();
        script.AppendLine("  ; File associations.");
        foreach (var association in associations)
        {
            var progId = config.App.Identifier + "." + association.Extensions[0].TrimStart('.');
            foreach (var extension in association.Extensions)
                script.AppendLine(
                    $"  WriteRegStr HKCU \"Software\\Classes\\.{Escape(extension.TrimStart('.'))}\" \"\" \"{Escape(progId)}\"");

            script.AppendLine($"  WriteRegStr HKCU \"Software\\Classes\\{Escape(progId)}\" \"\" \"{Escape(association.Description)}\"");
            script.AppendLine(
                $"  WriteRegStr HKCU \"Software\\Classes\\{Escape(progId)}\\shell\\open\\command\" \"\" " +
                $"'$\\\"$INSTDIR\\{Escape(exeName)}$\\\" $\\\"%1$\\\"'");
        }
    }

    private static void AppendProtocols(StringBuilder script, CarbonConfig config, string exeName)
    {
        var schemes = config.Bundle.Protocols.SelectMany(item => item.Schemes).Distinct().ToList();
        if (schemes.Count == 0) return;

        script.AppendLine();
        script.AppendLine("  ; Deep-link protocol handlers.");
        foreach (var scheme in schemes)
        {
            var key = $"Software\\Classes\\{Escape(scheme)}";
            script.AppendLine($"  WriteRegStr HKCU \"{key}\" \"\" \"URL:{Escape(scheme)}\"");
            script.AppendLine($"  WriteRegStr HKCU \"{key}\" \"URL Protocol\" \"\"");
            script.AppendLine(
                $"  WriteRegStr HKCU \"{key}\\shell\\open\\command\" \"\" " +
                $"'$\\\"$INSTDIR\\{Escape(exeName)}$\\\" $\\\"%1$\\\"'");
        }
    }

    /// <summary>
    /// The file name of a Windows path, split on both separators. <see cref="Path.GetFileName(string)"/>
    /// only honours the *host's* separator, so on macOS/Linux it returns a backslash path unchanged.
    /// </summary>
    internal static string WindowsFileName(string path) =>
        path[(path.LastIndexOfAny(['\\', '/']) + 1)..];

    /// <summary>VIProductVersion demands exactly four numeric parts.</summary>
    internal static string FileVersion(string version)
    {
        var numbers = version.Split(['.', '-', '+'], StringSplitOptions.RemoveEmptyEntries)
            .TakeWhile(part => part.All(char.IsAsciiDigit))
            .Take(4)
            .Select(part => int.TryParse(part, out var value) ? value : 0)
            .ToList();
        while (numbers.Count < 4) numbers.Add(0);
        return string.Join('.', numbers);
    }

    /// <summary>NSIS strings are double-quoted; <c>$</c> and <c>"</c> need escaping.</summary>
    private static string Escape(string value) =>
        value.Replace("$", "$$", StringComparison.Ordinal)
             .Replace("\"", "$\\\"", StringComparison.Ordinal);
}
