// AUTO-GENERATED by `carbon types` — do not edit.
import '@dotcarbon/api';
import type { CarbonPluginMetadata } from '@dotcarbon/api';

declare module '@dotcarbon/api' {
    interface CarbonCommands {
        'app:greet': { args: { name: string }; result: string };
    }
}

export declare const carbonGeneratedPluginMetadata: readonly CarbonPluginMetadata[];

export type CarbonGeneratedPluginMetadata = readonly [
    {
        readonly namespace: 'app';
        readonly name: 'AppCommands';
        readonly version: null;
        readonly description: null;
        readonly commands: readonly [
            {
                readonly name: 'greet';
                readonly fullName: 'app:greet';
                readonly arguments: 'GreetRequest';
                readonly result: 'string';
            },
        ];
        readonly permissions: readonly [];
        readonly events: readonly [];
    },
];
